import React, { useState, useRef } from 'react';
import Head from 'next/head';
import { Inter } from '@next/font/google';
import TodoList from './TodoList';
import { useAuthState } from "react-firebase-hooks/auth";
import { auth } from "../utils/firebase";
import {v4 as uuidv4} from 'uuid';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [todos, setTodos] = useState([]);
  const [user] = useAuthState(auth);
  const addRef = useRef();

  function addTodo(event){
    const listName = addRef.current.value
    if (listName){
      setTodos(oldTodos => {
        return [...oldTodos, {id:uuidv4(), name: listName, isComplete:false}]
      })
      addRef.current.value = null 
    } else{
      return null
    }
  }

  function checkBox(id) {
    const newItem = [...todos]
    const todo = newItem.find(specificItem => specificItem.id === id);
    todo.isComplete = !todo.isComplete
    setTodos(newItem)
  }

  function deleteTodos(){
    const newTodos = todos.filter(todo => !todo.isComplete)
    setTodos(newTodos)
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <div className="mx-6 md:max-w-2xl md:mx-auto">
      
      <div className= "flex justify-center text-white py-10">
        <h1 className="text-5xl font-bold shadow-lg rounded-lg px-2 border">Todo List</h1>
      </div>
      
      {user &&(
        <div>
          <div className='flex-row mb-2'>
            <TodoList todos={todos} checkBox={checkBox}/>
          </div>
          <span className="flex justify-center mb-2">  
            <input ref={addRef} type='text' className="rounded py-2 px-2" placeholder='Add todo...'></input>
          </span>
          <div className="flex justify-center gap-10">
            <button onClick={addTodo} className='font-bold text-white border py-1 rounded-lg shadow-lg bg-slate-600 px-2 hover:bg-violet-600'>Add Item</button>
            <button onClick={deleteTodos} className='font-bold text-white border py-1 rounded-lg shadow-lg bg-slate-600 px-2 hover:bg-violet-600'>Delete</button>
          </div>
          <p className='flex justify-center font-bold text-white py-1 mt-2 rounded-lg'>Left todo: {todos.length}</p>
        </div>
      )}

    </div>
      
    </>
  )
}
